apiVersion: apps/v1
kind: Deployment
metadata:
  name: fibonacci
  labels:
    app: fibonacci
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fibonacci 
  template:
    metadata:
      labels:
        app: fibonacci
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/metrics'
        prometheus.io/port: '3333'
    spec:
      # schedulerName: DefaultScheduler
      schedulerName: heuristic-scheduler
      nodeSelector:
        worker: "true"
        class: "active"
      containers:
      - name: fibonacci
        image: fibonacci:1.0
        imagePullPolicy: Never
        ports:
        - containerPort: 3333
        env:
        - name: FIBONACCI_TIMEOUT_SECONDS
          value: "1000"
        resources:
          limits:
            cpu: "500m"
          requests:
            cpu: "500m"