apiVersion: v1
kind: Service
metadata:
  name: fibonacci-nodeport
  labels:
    app: fibonacci-nodeport
spec:
  ports:
  - port: 3333
    targetPort: 3333
    nodePort: 30333
  selector:
    app: fibonacci
  type: NodePort 