apiVersion: kubescheduler.config.k8s.io/v1
kind: KubeSchedulerConfiguration
leaderElection:
  leaderElect: false
clientConnection:
  kubeconfig: "/etc/kubernetes/admin.conf"
profiles:
- schedulerName: heuristic-scheduler
  plugins:
    filter:
      enabled:
        - name: HeuristicScheduler
    preScore:
      enabled:
        - name: 'HeuristicScheduler'
    score:
      enabled:
        - name: 'HeuristicScheduler'
    postBind:
      enabled:
        - name: 'HeuristicScheduler'