apiVersion: v1
kind: Service
metadata:
  name: prometheus-clusterip
  labels:
    app: prometheus-clusterip
  namespace: monitoring
spec:
  ports:
  - port: 9090
    targetPort: 9090
  selector:
    app: prometheus