apiVersion: v1
kind: Service
metadata:
  name: prometheus-nodeport
  labels:
    app: prometheus-nodeport
spec:
  ports:
  - port: 9090
    targetPort: 9090
    nodePort: 31090
  selector:
    app: prometheus
  type: NodePort 
  