apiVersion: v1
clusters:
- cluster:
    certificate-authority: ./ca.crt
    extensions:
    - extension:
        last-update: Thu, 07 Sep 2023 08:58:10 +0330
        provider: minikube.sigs.k8s.io
        version: v1.31.2
      name: cluster_info
    server: https://192.168.49.2:8443
  name: thesis-cluster
contexts:
- context:
    cluster: thesis-cluster
    extensions:
    - extension:
        last-update: Thu, 07 Sep 2023 08:58:10 +0330
        provider: minikube.sigs.k8s.io
        version: v1.31.2
      name: context_info
    namespace: default
    user: thesis-cluster
  name: thesis-cluster
current-context: thesis-cluster
kind: Config
preferences: {}
users:
- name: thesis-cluster
  user:
    client-certificate: ./client.crt
    client-key: ./client.key
