apiVersion: v1
kind: Service
metadata:
  name: database-nodeport
  labels:
    app: database-nodeport
spec:
  ports:
  - port: 3306
    targetPort: 3306
    nodePort: 30306
  selector:
    app: database
  type: NodePort 