apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-agent
  labels:
    app: ai-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-agent
  template:
    metadata:
      labels:
        app: ai-agent
    spec:
      containers:
      - name: ai-agent
        image: ai_agent:0.4
        ports:
        - containerPort: 8080
        volumeMounts:
          - name:  ai-agent-volume
            mountPath: /app/src/storage
      nodeSelector:
        minikube.k8s.io/primary: "true"
      volumes:
        - name: ai-agent-volume
          hostPath:
            path: /pod_volumes/ai_agent
            type: Directory