version: '3.2'
networks:
  cluster:
    driver: bridge
services:
  mysql:
    networks:
      - cluster
    image: mysql:5.7
    restart: always
    ports:
      - 0.0.0.0:3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=9xz3jrd8wf
      - MYSQL_DATABASE=cluster
      - MYSQL_USER=sample_user
      - MYSQL_PASSWORD=9xz3jrd8wf
    volumes:
      - ./.volumes:/var/lib/mysql
