#!/bin/bash

export ENV=DEV_MINIKUBE
export CONFIG_DIR_DEV_MINIKUBE=./config/incluster_auth/config.yml
export CLUSTER_NAMESPACE=openfaas-fn

export DB_HOST=$DATABASE_NODEPORT_SERVICE_HOST
export DB_PORT=$DATABASE_NODEPORT_SERVICE_PORT
export DB_DATABASE=cluster
export DB_USERNAME=sample_user
export DB_PASSWORD=9xz3jrd8wf

# AI Agent
export AI_AGENT_URL=http://$AI_AGENT_NODEPORT_SERVICE_HOST:$AI_AGENT_NODEPORT_SERVICE_PORT

# Prometheus
export PROMETHEUS_URL=http://$PROMETHEUS_NODEPORT_SERVICE_HOST:$PROMETHEUS_NODEPORT_SERVICE_PORT

# Monitoring server
export MONITORING_SERVER_URL=http://$MONITORING_SERVER_NODEPORT_SERVICE_HOST:$MONITORING_SERVER_NODEPORT_SERVICE_PORT