apiVersion: v1
kind: Service
metadata:
  name: gateway-nodeport
  labels:
    app: gateway-nodeport
spec:
  ports:
  - port: 4444
    targetPort: 4444
    nodePort: 30444
  selector:
    app: gateway
  type: NodePort 