apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/metrics'
        prometheus.io/port: '4444'
    spec:
      containers:
      - name: gateway
        image: gateway:0.2
        ports:
        - containerPort: 4444