apiVersion: v1
kind: Service
metadata:
  name: monitoring-server-nodeport
  labels:
    app: monitoring-server-nodeport
spec:
  ports:
  - port: 5555
    targetPort: 5555
    nodePort: 32000
  selector:
    app: monitoring-server
  type: NodePort