kind: Deployment
apiVersion: apps/v1
metadata:
  name: fibonacci
  namespace: openfaas-fn
  uid: 906b3abb-387d-46ac-9a90-e116ceca6e8c
  resourceVersion: '77343'
  generation: 6
  creationTimestamp: '2023-02-12T17:54:03Z'
  labels:
    faas_function: fibonacci
  annotations:
    deployment.kubernetes.io/revision: '6'
    prometheus.io.scrape: 'false'
  managedFields:
    - manager: faas-netes
      operation: Update
      apiVersion: apps/v1
      time: '2023-02-12T17:54:03Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:prometheus.io.scrape: {}
          f:labels:
            .: {}
            f:faas_function: {}
        f:spec:
          f:progressDeadlineSeconds: {}
          f:replicas: {}
          f:revisionHistoryLimit: {}
          f:selector: {}
          f:strategy:
            f:rollingUpdate:
              .: {}
              f:maxSurge: {}
              f:maxUnavailable: {}
            f:type: {}
          f:template:
            f:metadata:
              f:annotations:
                .: {}
                f:prometheus.io.scrape: {}
              f:labels:
                .: {}
                f:faas_function: {}
              f:name: {}
            f:spec:
              f:containers:
                k:{"name":"fibonacci"}:
                  .: {}
                  f:image: {}
                  f:name: {}
                  f:ports:
                    .: {}
                    k:{"containerPort":8080,"protocol":"TCP"}:
                      .: {}
                      f:containerPort: {}
                      f:name: {}
                      f:protocol: {}
                  f:resources: {}
                  f:securityContext:
                    .: {}
                    f:readOnlyRootFilesystem: {}
                  f:terminationMessagePath: {}
                  f:terminationMessagePolicy: {}
              f:dnsPolicy: {}
              f:restartPolicy: {}
              f:schedulerName: {}
              f:securityContext: {}
              f:terminationGracePeriodSeconds: {}
    - manager: dashboard
      operation: Update
      apiVersion: apps/v1
      time: '2023-02-12T19:19:08Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:template:
            f:metadata:
              f:annotations:
                f:kubectl.kubernetes.io/restartedAt: {}
            f:spec:
              f:containers:
                k:{"name":"fibonacci"}:
                  f:imagePullPolicy: {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: apps/v1
      time: '2023-02-12T19:19:09Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:deployment.kubernetes.io/revision: {}
        f:status:
          f:availableReplicas: {}
          f:conditions:
            .: {}
            k:{"type":"Available"}:
              .: {}
              f:lastTransitionTime: {}
              f:lastUpdateTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
            k:{"type":"Progressing"}:
              .: {}
              f:lastTransitionTime: {}
              f:lastUpdateTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
          f:observedGeneration: {}
          f:readyReplicas: {}
          f:replicas: {}
          f:updatedReplicas: {}
      subresource: status
spec:
  replicas: 1
  selector:
    matchLabels:
      faas_function: fibonacci
  template:
    metadata:
      name: fibonacci
      creationTimestamp: null
      labels:
        faas_function: fibonacci
      annotations:
        kubectl.kubernetes.io/restartedAt: '2023-02-12T19:16:35Z'
        prometheus.io.scrape: 'false'
    spec:
      containers:
        - name: fibonacci
          image: kkphk/fibonacci:latest
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Never
          securityContext:
            readOnlyRootFilesystem: false
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 6
  replicas: 1
  updatedReplicas: 1
  readyReplicas: 1
  availableReplicas: 1
  conditions:
    - type: Available
      status: 'True'
      lastUpdateTime: '2023-02-12T19:19:09Z'
      lastTransitionTime: '2023-02-12T19:19:09Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2023-02-12T19:19:09Z'
      lastTransitionTime: '2023-02-12T19:09:45Z'
      reason: NewReplicaSetAvailable
      message: ReplicaSet "fibonacci-6494bf6768" has successfully progressed.
