apiVersion: v1
kind: Service
metadata:
  name: grafana-nodeport
  labels:
    app: grafana-nodeport
spec:
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 31010
  selector:
    app: grafana
  type: NodePort