apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      volumes:
        - name: grafana-storage-volume
          hostPath:
            path: /pod_volumes/grafana
            type: Directory
      nodeSelector:
        minikube.k8s.io/primary: "true"
      containers:
        - name: grafana
          image: "grafana/grafana@sha256:423040d62678074111e4e72d7dcef23480a94eb4f21b9173204d1a5ee972ec59"
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 500m
              memory: 500M
            limits:
              cpu: "1"
              memory: 1Gi
          volumeMounts:
            - name: grafana-storage-volume
              mountPath: /var/lib/grafana