apiVersion: batch/v1
kind: CronJob
metadata:
  name: random-scaler
spec:
  schedule: "* * * * *"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: random-scaler
        spec:
          nodeSelector:
            minikube.k8s.io/primary: "true"
          containers:
          - name: resource-manager
            image: scaler:1.0
            command: ["make", "run-random-scaler-bin"]
            env:
              - name: LOG_TO_CONSOLE
                value: "false"
              - name: LOG_FILE_DIR
                value: "/app/storage/random_scaler_logs.log"
            volumeMounts:
              - name:  random-scaler-volume
                mountPath: /app/storage
          volumes:
            - name: random-scaler-volume
              hostPath:
                path: /pod_volumes/resource_manager
                type: Directory
          restartPolicy: Never
